export const stateValue = [
    "Ahmedabad",
    "Alabama",
    "Alaska",
    "Alberta",
    "American Samoa",
    "Andaman & Nicobar",
    "Andrapradesh",
    "Anhui",
    "Arizona",
    "Arkansas",
    "Arunachal Pradesh",
    "Assam",
    "Australian Capital Territory",
    "Bangalore",
    "Baroda",
    "Beijing",
    "Bihar",
    "British Columbia",
    "California",
    "Chattisgargh",
    "Chennai",
    "Chongqing",
    "Cochin",
    "Colorado",
    "Connecticut",
    "Delaware",
    "Delhi",
    "Dist. of Columbia",
    "Federated States of Micronesia",
    "Florida",
    "Fujian",
    "Gansu",
    "Georgia",
    "Goa",
    "Guam",
    "Guangdong",
    "Guangxi",
    "Guizhou",
    "Gujarat",
    "Hainan",
    "Haryana",
    "Hawaii",
    "Hebei",
    "Heilongjiang",
    "Henan",
    "Himachal Pardesh",
    "Hong Kong Island",
    "Hubei",
    "Hunan",
    "Hyderabad",
    "Idaho",
    "Illinois",
    "Indiana",
    "Inner Mong",
    "Iowa",
    "Jiangsu",
    "Jiangxi",
    "Jilin",
    "Kansas",
    "Karnataka",
    "Kentucky",
    "Kerala",
    "Kolkata",
    "Kowloon",
    "Lantau Island",
    "Liaoning",
    "Louisiana",
    "Madhya Pradesh",
    "Maharashtra",
    "Maine",
    "Manipur",
    "Manitoba",
    "Marshall Islands",
    "Maryland",
    "Massachusetts",
    "Meghalaya",
    "Michigan",
    "Minnesota",
    "Mississippi",
    "Missouri",
    "Mizoram",
    "Montana",
    "Mumbai",
    "Mysore",
    "Nagaland",
    "Navi Mumbai",
    "Nebraska",
    "NeiMongol",
    "Nevada",
    "New Brunswick",
    "Newfoundland and Labrador",
    "New Hampshire",
    "New Jersey",
    "New Mexico",
    "New South Wales",
    "New Territories",
    "New York",
    "Ningxia",
    "North Carolina",
    "North Dakota",
    "Northern Mariana Islands",
    "Northern Territory",
    "Northwest Territories",
    "Nova Scotia",
    "Nunavut",
    "Ohio",
    "Oklahoma",
    "Ontario",
    "Oregon",
    "Orrisa",
    "Palau",
    "Pennsylvania",
    "Pondicherry",
    "Prince Edward Island",
    "Puerto Rico",
    "Pune",
    "Punjab",
    "Qinghai",
    "Quebec",
    "Queensland",
    "Rajasthan",
    "Rhode Island",
    "Saskatchewan",
    "Secunderabad",
    "Shaanxi",
    "Shandong",
    "Shanghai",
    "Shanxi",
    "Sichuan",
    "Singapore",
    "South Australia",
    "South Carolina",
    "South Dakota",
    "Surat",
    "Tamil Nadu",
    "Tasmania",
    "Tennessee",
    "Texas",
    "Thiruvananthapuram",
    "Tianjin",
    "Tibet",
    "Tripura",
    "Utah",
    "Uttar Pradesh",
    "Uttrakhand",
    "Vermont",
    "Victoria",
    "Virginia",
    "Virgin Islands",
    "Washington",
    "West Bangal",
    "Western Australia",
    "West Virginia",
    "Wisconsin",
    "Wyoming",
    "Xinjiang",
    "Xizang",
    "Yukon",
    "Yunnan",
    "Zhejiang",
    "APO/AE",
    "AFO/FPO",
    "FPO",
    "AP"
 ]


 export const industry = [
    "Aerospace",
    "Agriculture",
    "Automotive",
    "Computers & Electronics",
    "Consumer Goods",
    "Education",
    "Financial Services",
    "Gaming",
    "Government",
    "Healthcare",
    "Hospitality",
    "Life Sciences",
    "Manufacturing",
    "Marketing & Advertising",
    "Media & Entertainment",
    "Mining",
    "Non-Profit Organization",
    "Oil & Gas",
    "Other",
    "Power & Utilities",
    "Professional Services",
    "Real Estate & Construction",
    "Retail",
    "Software & Internet",
    "Telecommunications",
    "Transportation & Logistics",
    "Travel",
    "Wholesale & Distribution"
 ]